SELECT
    A.APNT_NO,
    P.PT_NAME,
    P.PT_NO,
    A.MCDP_CD,
    D.DR_NAME,
    A.APNT_YMD
FROM
    PATIENT P
    JOIN
    APPOINTMENT A
        ON P.PT_NO = A.PT_NO
    JOIN
    DOCTOR D
        ON A.MDDR_ID = D.DR_ID
WHERE
    TO_CHAR(A.APNT_YMD,'YYYY-MM-DD')='2022-04-13'
    AND
    A.APNT_CNCL_YN='N'
ORDER BY A.APNT_YMD;