SELECT
    EXTRACT(MONTH FROM START_DATE) MONTH,
    CAR_ID,
    COUNT(*) RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    DATE '2022-08-01' <= START_DATE
    AND START_DATE < DATE '2022-11-01'
    AND CAR_ID IN (
        SELECT
            CAR_ID
            FROM
                CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE
                DATE '2022-08-01' <= START_DATE
                AND START_DATE < DATE '2022-11-01'
            GROUP BY CAR_ID
            HAVING COUNT(*)>=5
        )
GROUP BY
    EXTRACT(MONTH FROM START_DATE),
    CAR_ID
ORDER BY
    MONTH,
    CAR_ID DESC