WITH HOURS AS (
    SELECT LEVEL-1 HOUR
    FROM DUAL
    CONNECT BY LEVEL<=24
)

SELECT
    HOUR,
    (
        SELECT COUNT(*)
        FROM ANIMAL_OUTS
        WHERE HOUR=EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
    ) COUNT
FROM HOURS
ORDER BY HOUR;