SELECT
    MONTH,
    CAR_ID,
    COUNT(*) RECORDS
FROM (
    SELECT
        EXTRACT(MONTH FROM START_DATE) MONTH,
        CAR_ID,
        COUNT(*) OVER (PARTITION BY CAR_ID) TOTAL
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        DATE '2022-08-01' <= START_DATE
        AND START_DATE <  DATE '2022-11-01'
    )
WHERE TOTAL >= 5
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC