WITH MILK AS (
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
),
YOGURT AS (
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
)

SELECT M.CART_ID
FROM MILK M JOIN YOGURT Y ON M.CART_ID = Y.CART_ID
ORDER BY CART_ID