WITH HOURS AS (
    SELECT LEVEL-1 HOUR
    FROM DUAL
    CONNECT BY LEVEL<=24
)

SELECT
    H.HOUR,
    COUNT(A.ANIMAL_ID) COUNT
FROM
    HOURS H
    LEFT JOIN ANIMAL_OUTS A
    ON H.HOUR = EXTRACT(HOUR FROM CAST(A.DATETIME AS TIMESTAMP))
GROUP BY H.HOUR
ORDER BY H.HOUR;