WITH H00 AS (SELECT  0 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '00'),
     H01 AS (SELECT  1 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '01'),
     H02 AS (SELECT  2 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '02'),
     H03 AS (SELECT  3 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '03'),
     H04 AS (SELECT  4 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '04'),
     H05 AS (SELECT  5 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '05'),
     H06 AS (SELECT  6 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '06'),
     H07 AS (SELECT  7 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '07'),
     H08 AS (SELECT  8 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '08'),
     H09 AS (SELECT  9 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '09'),
     H10 AS (SELECT 10 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '10'),
     H11 AS (SELECT 11 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '11'),
     H12 AS (SELECT 12 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '12'),
     H13 AS (SELECT 13 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '13'),
     H14 AS (SELECT 14 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '14'),
     H15 AS (SELECT 15 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '15'),
     H16 AS (SELECT 16 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '16'),
     H17 AS (SELECT 17 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '17'),
     H18 AS (SELECT 18 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '18'),
     H19 AS (SELECT 19 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '19'),
     H20 AS (SELECT 20 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '20'),
     H21 AS (SELECT 21 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '21'),
     H22 AS (SELECT 22 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '22'),
     H23 AS (SELECT 23 HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS WHERE TO_CHAR(DATETIME, 'HH24') = '23')

SELECT HOUR, COUNT           FROM H00
UNION ALL SELECT HOUR, COUNT FROM H01
UNION ALL SELECT HOUR, COUNT FROM H02
UNION ALL SELECT HOUR, COUNT FROM H03
UNION ALL SELECT HOUR, COUNT FROM H04
UNION ALL SELECT HOUR, COUNT FROM H05
UNION ALL SELECT HOUR, COUNT FROM H06
UNION ALL SELECT HOUR, COUNT FROM H07
UNION ALL SELECT HOUR, COUNT FROM H08
UNION ALL SELECT HOUR, COUNT FROM H09
UNION ALL SELECT HOUR, COUNT FROM H10
UNION ALL SELECT HOUR, COUNT FROM H11
UNION ALL SELECT HOUR, COUNT FROM H12
UNION ALL SELECT HOUR, COUNT FROM H13
UNION ALL SELECT HOUR, COUNT FROM H14
UNION ALL SELECT HOUR, COUNT FROM H15
UNION ALL SELECT HOUR, COUNT FROM H16
UNION ALL SELECT HOUR, COUNT FROM H17
UNION ALL SELECT HOUR, COUNT FROM H18
UNION ALL SELECT HOUR, COUNT FROM H19
UNION ALL SELECT HOUR, COUNT FROM H20
UNION ALL SELECT HOUR, COUNT FROM H21
UNION ALL SELECT HOUR, COUNT FROM H22
UNION ALL SELECT HOUR, COUNT FROM H23
ORDER BY HOUR;