SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK B
    JOIN AUTHOR A
        ON B.AUTHOR_ID=A.AUTHOR_ID
    JOIN BOOK_SALES BS
        ON B.BOOK_ID=BS.BOOK_ID
WHERE
    DATE '2022-01-01' <= BS.SALES_DATE
        AND BS.SALES_DATE < DATE '2022-02-01'
GROUP BY
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY
ORDER BY
    A.AUTHOR_ID,
    B.CATEGORY DESC