WITH RENTAL_HISTORY_WITH_DURATION_TYPE AS (
    SELECT
        HISTORY_ID,
        CAR_ID,
        END_DATE - START_DATE + 1 DURATION,
        CASE
            WHEN (END_DATE - START_DATE + 1) >= 90 THEN '90일 이상'
            WHEN (END_DATE - START_DATE + 1) >= 30 THEN '30일 이상'
            WHEN (END_DATE - START_DATE + 1) >= 7 THEN '7일 이상'
            ELSE NULL
        END DURATION_TYPE
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT
    H.HISTORY_ID HISTORY_ID,
    H.DURATION * C.DAILY_FEE * (1 - (NVL(D.DISCOUNT_RATE, 0) / 100)) FEE
FROM
    RENTAL_HISTORY_WITH_DURATION_TYPE H
    JOIN CAR_RENTAL_COMPANY_CAR C
        ON H.CAR_ID = C.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
        ON C.CAR_TYPE = D.CAR_TYPE AND H.DURATION_TYPE = D.DURATION_TYPE
WHERE
    C.CAR_TYPE = '트럭'
ORDER BY
    FEE DESC,
    H.HISTORY_ID DESC