SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI
JOIN ANIMAL_OUTS AO
    ON AI.ANIMAL_ID=AO.ANIMAL_ID
WHERE SUBSTR(AI.SEX_UPON_INTAKE,0,6) = 'Intact'
    AND SUBSTR(AO.SEX_UPON_OUTCOME,0,6) != 'Intact'
ORDER BY ANIMAL_ID